name: esc_pos_bluetooth
description: The library allows to print receipts using an ESC/POS thermal Bluetooth printer.
version: 0.4.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/andrey-ushakov/esc_pos_bluetooth

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  esc_pos_utils: ^1.1.0
  # esc_pos_utils:
  # path: ../esc_pos_utils
  flutter_bluetooth_basic:
    path: ../flutter_bluetooth_basic

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
